SECOND = 1000
DEFAULT_WAIT_TIME_SEC = 5
DEFAULT_WAIT_TIME_MS = DEFAULT_WAIT_TIME_SEC * SECOND

XPATH_LOCATOR = "xpath"
CSS_LOCATOR = "css"
DEFAULT_LOCATOR_TYPE = XPATH_LOCATOR

DEFAULT_BROWSER_DEBUGGER_ADDRESS = "http://127.0.0.1:9222"

CHROME_BROWSER = "ChromeBrowser"
FIREFOX_BROWSER = "FireFoxBrowser"
REMOTE_CHROME_BROWSER = "Remote" + CHROME_BROWSER
REMOTE_FIREFOX_BROWSER = "Remote" + FIREFOX_BROWSER
BROWSERS = [CHROME_BROWSER, FIREFOX_BROWSER, REMOTE_CHROME_BROWSER, REMOTE_FIREFOX_BROWSER]

DEFAULT_VIEWPORT_SIZE = {"width": 1280, "height": 1024}
PLAYWRIGHT_PAGE_DEFAULT_TIMEOUT_SEC = 20
PLAYWRIGHT_PAGE_DEFAULT_TIMEOUT_MS = PLAYWRIGHT_PAGE_DEFAULT_TIMEOUT_SEC * SECOND
PLAYWRIGHT_DEFAULT_LOCALE = "en"

LOG_TIME_STRUCTURE = "-%Y-%m-%d-%H%M-%S"
